-- Demo logging tables for the Supabase project that receives prospect-demo telemetry.
-- Run this in the correct Supabase project:
--   https://drhgrgodupwcauijpukz.supabase.co

-- Shared chat-log shape for all four demo modes.
CREATE TABLE IF NOT EXISTS demo_single_model_logs (
    id              BIGSERIAL PRIMARY KEY,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    venue_id        TEXT NOT NULL,
    venue_name      TEXT NOT NULL,
    prospect_name   TEXT NOT NULL,
    question        TEXT NOT NULL,
    response        TEXT NOT NULL,
    demo_mode       TEXT NOT NULL DEFAULT 'single_model'
        CHECK (demo_mode = 'single_model')
);

CREATE TABLE IF NOT EXISTS demo_council_logs (
    id              BIGSERIAL PRIMARY KEY,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    venue_id        TEXT NOT NULL,
    venue_name      TEXT NOT NULL,
    prospect_name   TEXT NOT NULL,
    question        TEXT NOT NULL,
    response        TEXT NOT NULL,
    demo_mode       TEXT NOT NULL DEFAULT 'council'
        CHECK (demo_mode = 'council')
);

CREATE TABLE IF NOT EXISTS demo_prism_logs (
    id              BIGSERIAL PRIMARY KEY,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    venue_id        TEXT NOT NULL,
    venue_name      TEXT NOT NULL,
    prospect_name   TEXT NOT NULL,
    question        TEXT NOT NULL,
    response        TEXT NOT NULL,
    demo_mode       TEXT NOT NULL DEFAULT 'prism'
        CHECK (demo_mode = 'prism')
);

CREATE TABLE IF NOT EXISTS demo_council_prism_logs (
    id              BIGSERIAL PRIMARY KEY,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    venue_id        TEXT NOT NULL,
    venue_name      TEXT NOT NULL,
    prospect_name   TEXT NOT NULL,
    question        TEXT NOT NULL,
    response        TEXT NOT NULL,
    demo_mode       TEXT NOT NULL DEFAULT 'council_prism'
        CHECK (demo_mode = 'council_prism')
);

CREATE INDEX IF NOT EXISTS idx_demo_single_model_logs_venue
    ON demo_single_model_logs (venue_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_demo_single_model_logs_prospect
    ON demo_single_model_logs (prospect_name, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_demo_council_logs_venue
    ON demo_council_logs (venue_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_demo_council_logs_prospect
    ON demo_council_logs (prospect_name, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_demo_prism_logs_venue
    ON demo_prism_logs (venue_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_demo_prism_logs_prospect
    ON demo_prism_logs (prospect_name, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_demo_council_prism_logs_venue
    ON demo_council_prism_logs (venue_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_demo_council_prism_logs_prospect
    ON demo_council_prism_logs (prospect_name, created_at DESC);

COMMENT ON TABLE demo_single_model_logs IS
    'Mode 1 demo chat exchanges generated by the single-model prospect demo.';
COMMENT ON TABLE demo_council_logs IS
    'Mode 2 demo chat exchanges generated by the council prospect demo.';
COMMENT ON TABLE demo_prism_logs IS
    'Mode 3 demo chat exchanges generated by the Prism prospect demo.';
COMMENT ON TABLE demo_council_prism_logs IS
    'Mode 4 demo chat exchanges generated by the council plus Prism prospect demo.';

-- Detailed Prism pipeline tracking stays separate because only modes 3 and 4 run Prism.
CREATE TABLE IF NOT EXISTS demo_prism_sessions (
    id                  BIGSERIAL PRIMARY KEY,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    venue_id            TEXT NOT NULL,
    venue_name          TEXT NOT NULL,
    prospect_name       TEXT NOT NULL,
    demo_level          INT NOT NULL CHECK (demo_level = 3),
    question            TEXT NOT NULL,
    full_response       TEXT NOT NULL,
    duration_ms         INT,
    agents_completed    INT NOT NULL DEFAULT 6,
    agents_errored      TEXT[] NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS demo_council_prism_sessions (
    id                  BIGSERIAL PRIMARY KEY,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    venue_id            TEXT NOT NULL,
    venue_name          TEXT NOT NULL,
    prospect_name       TEXT NOT NULL,
    demo_level          INT NOT NULL CHECK (demo_level = 4),
    question            TEXT NOT NULL,
    full_response       TEXT NOT NULL,
    duration_ms         INT,
    agents_completed    INT NOT NULL DEFAULT 6,
    agents_errored      TEXT[] NOT NULL DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS idx_demo_prism_sessions_venue
    ON demo_prism_sessions (venue_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_demo_prism_sessions_prospect
    ON demo_prism_sessions (prospect_name, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_demo_council_prism_sessions_venue
    ON demo_council_prism_sessions (venue_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_demo_council_prism_sessions_prospect
    ON demo_council_prism_sessions (prospect_name, created_at DESC);

COMMENT ON TABLE demo_prism_sessions IS
    'Detailed Prism pipeline runs for pure Prism demo mode (mode 3).';
COMMENT ON TABLE demo_council_prism_sessions IS
    'Detailed Prism pipeline runs for council plus Prism demo mode (mode 4).';
